### ISSUE TITLE
uwu what's this?

### ISSUE THREAD

**Issue by cr1ptik** [TT-Tutorials/GANG-Nuker#23]
![image](https://user-images.githubusercontent.com/68492220/150057621-96ceabb5-7409-4798-a277-1b9fc5b3475e.png)

**Comment by nerotion** [comment]
LMAO

**Comment by hsilver10** [comment]
?

**Comment by cr1ptik** [comment]
> ?

it's a token logger

**Comment by cr1ptik** [comment]
woa dude not cool
